language: python
dist: xenial
sudo: required

python:
  - "2.7.14"

addons:
#  code_climate:
#    repo_token: f7fa84853f7688638c4692deda36f9c85b4c4099fd42da5a6e7097c2f29cd651
  postgresql: "9.5"
  apt:
    packages:
    - libpq5
    - libpq-dev
    - apache2
    - apache2-dev
    - python-dev

before_install:
    - export DISPLAY=:99.0
    - sudo apt-get -qq update
    - sleep 10
    - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - psql -c 'create database stun;' -U postgres
  - python stun/manage.py migrate

before_script:
  - npm install --global karma requirejs jasmine-core karma-jasmine karma-requirejs karma-chrome-launcher karma-safari-launcher karma-ie-launcher karma-firefox-launcher karma-browserstack-launcher

script:
  - python stun/manage.py test
  - coverage run stun/manage.py test
  - karma start karma.conf.js --single-run

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
