language: python
sudo: required

python:
  - "2.7"

services:
  - postgresql

addons:
#  code_climate:
#    repo_token: f7fa84853f7688638c4692deda36f9c85b4c4099fd42da5a6e7097c2f29cd651
  apt:
    packages:
    - libpq-dev
    - python-dev
    - python-psycopg2

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database stun;' -U postgres
  - python stun/manage.py makemigrations 
  - python stun/manage.py migrate 
  - python stun/manage.py makemigrations app 
  - python stun/manage.py migrate app
  - npm install

script:
  - python stun/manage.py test
  - coverage run stun/manage.py test
  - node_modules/karma/bin/karma start karma.conf.js --single-run

after_success: coveralls

notifications:
  slack: lacnic-eng:jSDKPP0pyOgA5JV4lsQTGtuP
