# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 22:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StunMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_test_date', models.DateTimeField(default=datetime.datetime(2016, 6, 2, 22, 7, 59, 734388, tzinfo=utc))),
                ('client_test_date', models.DateTimeField(default=datetime.datetime(2016, 6, 2, 22, 7, 59, 734455, tzinfo=utc))),
                ('experiment_id', models.TextField(default='')),
                ('length', models.IntegerField(default=0)),
                ('candidate', models.TextField(default='')),
                ('number', models.BigIntegerField(default=0)),
                ('protocol', models.TextField(default='')),
                ('sequence', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(default='127.0.0.1')),
                ('sequence2', models.BigIntegerField(default=0)),
                ('typ', models.TextField(default='')),
                ('host', models.TextField(default='')),
                ('generation', models.TextField(default='')),
                ('active', models.TextField(default='')),
                ('number2', models.BigIntegerField(default=0)),
                ('ufrag', models.TextField(default='')),
                ('hash', models.TextField(default='')),
                ('tcptype', models.TextField(default='')),
            ],
        ),
    ]
