# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 23:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160602_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stunmeasurement',
            name='client_test_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 23, 31, 1, 432925, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='stunmeasurement',
            name='server_test_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 23, 31, 1, 432882, tzinfo=utc)),
        ),
    ]
